-- MySQL Script generated by MySQL Workbench
-- Sun Aug 28 16:40:34 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema emojiban
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema emojiban
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emojiban` DEFAULT CHARACTER SET utf8mb4 ;
USE `emojiban` ;

-- -----------------------------------------------------
-- Table `ROLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ROLE` ;

CREATE TABLE IF NOT EXISTS `ROLE` (
  `ID` CHAR(3) NOT NULL,
  `NAME` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;